/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F293_6411();
extern void F295_6573();
extern void F293_6415();
extern void F296_6577();
extern void F298_6741();
extern void F296_6582();
extern void F389_4156();
extern void F358_6257();
extern void F145_1701();
extern EIF_REFERENCE F145_1688();
extern EIF_BOOLEAN F145_1700();
extern EIF_BOOLEAN F145_1708();
extern void F145_1710();
extern void F145_1711();
extern void F145_1712();
extern void F88_1373();
extern EIF_TYPED_VALUE F88_1374();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F293_6411;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F293_6415;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F296_6577;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F296_6582;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F389_4156;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F295_6573;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F298_6741;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F358_6257;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F145_1701;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F145_1700;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F145_1688;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F145_1708;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F145_1710;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F145_1711;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F145_1712;

	egc_str_dtype = 294;

	egc_immstr8_dtype = 293;

	egc_str32_dtype = 297;

	egc_immstr32_dtype = 296;
	egc_arr_dtype = 388;
	egc_tup_dtype = 243;
	egc_disp_rout_id = 2374;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0266;
	egc_sp_wchar = 0x0242;
	egc_sp_bool = 0x021E;
	egc_sp_uint8 = 0x0296;
	egc_sp_uint16 = 0x03AA;
	egc_sp_uint32 = 0x01A6;
	egc_sp_uint64 = 0x01EE;
	egc_sp_int8 = 0x0362;
	egc_sp_int16 = 0x033E;
	egc_sp_int32 = 0x01D2;
	egc_sp_int64 = 0x0386;
	egc_sp_real32 = 0x02F6;
	egc_sp_real64 = 0x031A;
	egc_sp_pointer = 0x02D2;
	egc_sp_ref = 0x0187;

	egc_uint8_dtype = 266;
	egc_uint16_dtype = 263;
	egc_uint32_dtype = 260;
	egc_uint64_dtype = 257;
	egc_int8_dtype = 254;
	egc_int16_dtype = 251;
	egc_int32_dtype = 284;
	egc_int64_dtype = 248;
	egc_bool_dtype = 281;
	egc_real32_dtype = 269;
	egc_char_dtype = 278;
	egc_wchar_dtype = 275;
	egc_real64_dtype = 272;
	egc_point_dtype = 287;

	egc_exception_dtype = 104;
	egc_except_emnger_dtype = 144;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_http";
	egc_system_location = "D:\\prod\\simple_http\\EIFGENs\\simple_http_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1765230095;
	egc_has_old_special_semantic = 0;
	scount = 1078;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "HTTP_TEST_APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1107;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2910;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5594;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 87;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F88_1373;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F88_1374;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 64; /* HTTP_TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 204; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 318; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
